[project]
name = "rush-hour"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.11",
    "icecream>=2.1.3",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
]
